#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"

if [[ $1 == couchdb:* ]]; then
  if [[ -z $2 ]]; then
    dokku_log_fail "You must specify an app name"
  else
    APP="$2"
  fi
fi

COUCHDB_CONTAINER_NAME="couchdb-$APP"
COUCHDB_FLAG_PERSISTENCE_FILE="$DOKKU_ROOT/$APP/COUCHDB"
COUCHDB_VOLUME_DIR="$DOKKU_ROOT/.couchdb-mc/volume-$APP"
COUCHDB_CONTAINER_ID=$(docker ps | grep "$COUCHDB_CONTAINER_NAME" |  awk '{print $1}') || true
COUCHDB_PORT=5984

case "$1" in
  couchdb:enable)
    verify_app_name "$APP"
    dokku_log_info1 "Enabling CouchDB for $APP..."
    COUCHDB_PASS=$(openssl rand -hex 32)
    echo "$COUCHDB_PASS" > "$COUCHDB_FLAG_PERSISTENCE_FILE"
    chmod 600 "$COUCHDB_FLAG_PERSISTENCE_FILE"
    dokku config:set --no-restart "$APP" COUCH_URL="http://admin:$COUCHDB_PASS@couchdb:$COUCHDB_PORT/" COUCH_USER=admin COUCH_PASS="$COUCHDB_PASS" COUCH_PORT="$COUCHDB_PORT" COUCH_HOST=couchdb
    dokku docker-options:add "$APP" build,run,deploy "--link $COUCHDB_CONTAINER_NAME:couchdb"
    dokku_log_info2 "CouchDB enabled for $APP"
    dokku_log_verbose "CouchDB will be started on next build / deploy"
    ;;

  couchdb:destroy)
    if [[ ! -f "$COUCHDB_FLAG_PERSISTENCE_FILE" ]] && [[ ! -d $COUCHDB_VOLUME_DIR ]] && [[ -z $COUCHDB_CONTAINER_ID ]] && [[ -z $(dokku config:get "$APP" COUCHDB_URL) ]]; then
      dokku_log_info2 "No CouchDB instance / leftovers found for $APP"
      exit 0
    fi
    dokku_log_info1 "Destroying CouchDB for $APP..."
    if [[ -f "$COUCHDB_FLAG_PERSISTENCE_FILE" ]]; then
      rm "$COUCHDB_FLAG_PERSISTENCE_FILE"
    fi
    if [[ -n "$COUCHDB_CONTAINER_ID" ]]; then
      docker rm -f "$COUCHDB_CONTAINER_ID" > /dev/null
    fi
    if [[ -d $COUCHDB_VOLUME_DIR ]]; then
        rm -rf "$COUCHDB_VOLUME_DIR"
    fi
    dokku config:unset --no-restart "$APP" COUCH_URL COUCH_USER COUCH_PASS COUCH_PORT COUCH_HOST
    dokku docker-options:remove "$APP" build,run,deploy "--link $COUCHDB_CONTAINER_NAME:couchdb"
    dokku_log_info2 "CouchDB instance / volume destroyed:"
    dokku_log_verbose "Application: $APP"
    ;;

  help)
    cat && cat<<EOF
    couchdb:enable <app>, Enable CouchDB for an app for next build/deploy
    couchdb:destroy <app>, Destroy CouchDB container and volume of an app
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
